import { Bank } from '@shared/service-proxies/service-proxies';

export const bankLabels: Record<number, string> = {
    [Bank.Vietcombank]: 'Ngân hàng TMCP Ngoại thương Việt Nam',
    [Bank.Techcombank]: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    [Bank.VPBank]: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    [Bank.Vietinbank]: 'Ngân hàng TMCP Công thương Việt Nam',
    [Bank.BIDV]: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    [Bank.MB]: 'Ngân hàng TMCP Quân đội',
    [Bank.SHB]: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    [Bank.Agribank]: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    [Bank.ACB]: 'Ngân hàng TMCP Á Châu',
    [Bank.Sacombank]: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    [Bank.HDBank]: 'Ngân hàng TMCP Phát triển TP. Hồ Chí Minh',
    [Bank.VIB]: 'Ngân hàng TMCP Quốc tế Việt Nam',
    [Bank.TPBank]: 'Ngân hàng TMCP Tiên Phong',
    [Bank.MSB]: 'Ngân hàng TMCP Hàng hải Việt Nam',
    [Bank.OCB]: 'Ngân hàng TMCP Phương Đông',
    [Bank.SeABank]: 'Ngân hàng TMCP Đông Nam Á',
    [Bank.Eximbank]: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    [Bank.LPBank]: 'Ngân hàng TMCP Lộc Phát Việt Nam',
    [Bank.NamABank]: 'Ngân hàng TMCP Nam Á',
    [Bank.ABBank]: 'Ngân hàng TMCP An Bình',
    [Bank.PVcomBank]: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    [Bank.BacABank]: 'Ngân hàng TMCP Bắc Á',
    [Bank.Kienlongbank]: 'Ngân hàng TMCP Kiên Long',
    [Bank.BVBank]: 'Ngân hàng TMCP Bản Việt',
    [Bank.Saigonbank]: 'Ngân hàng TMCP Sài Gòn Công Thương',
    [Bank.PGBank]: 'Ngân hàng TMCP Xăng dầu Petrolimex',
    [Bank.NCB]: 'Ngân hàng TMCP Quốc Dân',
    [Bank.VietABank]: 'Ngân hàng TMCP Việt Á',
    [Bank.BaoVietBank]: 'Ngân hàng TMCP Bảo Việt',
    [Bank.VietBank]: 'Ngân hàng TMCP Việt Nam Thương Tín',
    [Bank.SCB]: 'Ngân hàng TMCP Sài Gòn',
    [Bank.DongABank]: 'Ngân hàng TMCP Đông Á',
    [Bank.GPBank]: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    [Bank.OceanBank]: 'Ngân hàng Thương mại TNHH MTV Đại Dương',
    [Bank.CBBank]: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
    [Bank.Coopbank]: 'Ngân hàng Hợp tác xã Việt Nam',
};

export const bankOptions = Object.keys(bankLabels).map((key) => ({
    value: Number(key) as Bank,
    label: bankLabels[Number(key)],
}));
